apiVersion: v1
kind: Secret
metadata:
    name: demoapp-credentials
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:6ph4zC4=,iv:E+Ah2ABDQ67Y5007JZeReRsFyzqXUZPvInZHDB6V5Qk=,tag:J07f8dQn4drxe9y2u6W3XQ==,type:str]
    password: ENC[AES256_GCM,data:ilvwC9Hq,iv:EIDNEp001nI1Y6EGj17ojGtng1ZBhTIOueFp4jGKfXU=,tag:WRs9nZucd9PywdRiSmcIeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://gitopsdemokeyvaultgirish.vault.azure.net
          name: sops-key
          version: 4678939e609b4cf0bf1381140b248e35
          created_at: "2021-09-11T13:06:22Z"
          enc: R2FdJGufKzR7IOMGad7lVaMUfPc2EhDCK_rQES-G3FYDWEFP0Pytfb8Yrp2VGY3X5gRnvaXqTSI1KKQwp9tTW7vRkjgLLzBslHCZ64-Ae1r4wX2cGmpIMWlR9uyjfOo1ZBKJQUpTZAP5XPg6DXwL6PSKSaTgoq4iPM9XayxeNadkClVTRUS5DQ4gXlloQWh6udGmgOgaJcnhDpYcwJuT5oVR8pg6IBc_1kE8rip_1rGFiUqG9gxzjDaJChkyhtWraaAdpfmpBn5dUL67kuKFY9o1FbJcBY7AwkA_divKsTMCWnK9auDvvxYlG-tDQNEyEVMxVD9GL6q04ZjWkJoqkw
    hc_vault: []
    age: []
    lastmodified: "2021-09-11T13:06:27Z"
    mac: ENC[AES256_GCM,data:jStKQNx+eoYP3f2JoWs0fhTEdtyysw41SYxzMeuVGIEhMntctS4I2/H3y9m0SNO5AFCY7Lhi7UxXr9wID1HFb6RHAkrduThX81JzneAqcot4cD1VAxI5HAQn2WnoXa8hjTWm4+G9zi3lTVR0A1BxTKwFSKTUqB51WfGzXBE5FSY=,iv:od+VEztWFBfenUCJLtvbb6BG52Vk+WtjlFZ1rnEGA6E=,tag:J09iedJVPNpnEQvkjVh1Ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
