apiVersion: v1
kind: Secret
metadata:
    name: demoapp-credentials
    namespace: demoapp
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8AGnlmQ=,iv:gyyuJB34k8cqjZ0qb0zNaryR9+XQx0RZiJVZwc5raWM=,tag:EDhY/hnnwwS5swnhH2yLqQ==,type:str]
    password: ENC[AES256_GCM,data:F/jPGpG8hKmDjA==,iv:rZiF503+u2u6nIi2Aj3k9HM8bc0/IDvuj3J57ACIEa8=,tag:5M3RGApTFxg6ZBNRpJvmUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://vaultgitops3.vault.azure.net
          name: sops-key
          version: 3809539ab2504ecca7c1c6dfb671ff94
          created_at: "2021-09-12T07:31:50Z"
          enc: Cw1hgRom_-P7athXNdY3a4-0W8ha5mzxi7NKuBb8bM7RG3gtn7FdjAss7qzP_Dp9eyz96I9eUaCyV68R6Kkat14h1AykVSaUF_LxRljD6H4Dlp5n0wKFQGNyJdxg5CrBGKDwO6IXf5vn6ihciTmiCHO5zhzru4UaLNHUYgvBdnxAfKwNSlW4aFxmWsibX0QNd4ZsNapCbsJQuWWFNFvJWYz1iAnRL_N4cLWWQ_MjNYmRR3CBm3LjTKPKamAXZwT6VGrBjvMuMUOpvEVnqBe_wQiCp1xhIQauvQlCxVMHjqWipT1ySrDSGG3VUh_wA6cT7AnaqFpVHcekdU_9VVH0_w
    hc_vault: []
    age: []
    lastmodified: "2021-09-12T07:31:53Z"
    mac: ENC[AES256_GCM,data:EpQDRFo0drUXwX3V3RFsG7/iEsydzdC9eQNfylWtdaZA3pw6E0H82FJTVaMsi0XwODrxD2Gn3mC2eXQIymTaHkxXdpsMnfCdUY712P9ekw7rP7QoducRVpZ2NOG79IaiOo6ky7DTvqincKJQi6cUx2/trCx1SZVW1xQQLRgwYnc=,iv:CZ4g+NjOrPvAxujeD94xWsMggEe0sQjDClSlupu90H8=,tag:Z3Q/TEZHXyWJh59SfwoSlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
